const A=()=>document.querySelector('#app');
let data={submissions:[],stories:[],behaviors:[],users:[]};
const save=()=>{};
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||'حدث خطأ');return j}
function asFile(input){return new Promise(resolve=>{const f=input.files?.[0];if(!f)return resolve(null);if(f.size>100*1024*1024){alert('الحد الأقصى للفيديو هو 100 MB');return resolve(null)}const r=new FileReader();r.onload=()=>resolve({name:f.name,data:r.result});r.readAsDataURL(f)})}
let role='';let user={};
const labels={student:'طالب',teacher:'معلم / معلمة',parent:'وليّ أمر',deputy:'نائب المدير',director:'المدير'};
function injectUIStyles(){if(document.querySelector('#afaq-extra-style'))return;document.head.insertAdjacentHTML('beforeend','<style id="afaq-extra-style">.school-name{color:#624cc7;font-size:22px;font-weight:800;margin-bottom:8px}.hero.single{justify-content:center;text-align:center}.nav-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#e65966;margin-right:7px;vertical-align:middle}.side nav button .nav-dot{float:left;margin-top:6px}</style>')}
injectUIStyles();
const nav={student:['الرئيسية','الميثاق','على خطى زايد','القيم الإيجابية','سفيرات الميثاق','نتائجي','شهاداتي'],teacher:['الرئيسية','إرسال سلوك إيجابي','شهاداتي'],parent:['الرئيسية','شراكة الأسرة','طلباتي السابقة','شهاداتي'],deputy:['الرئيسية','قيم الشهر','تقييم على خطى زايد','تقييم القيم الإيجابية','تقييم سفيرات الميثاق','تقييم السلوك الإيجابي','تقييم قصص النجاح','الفصل الإيجابي','المستخدمون'],director:['الرئيسية','الإحصائيات والنتائج']};
function landing(){A().innerHTML=`<section class="landing"><nav class="nav"><div class="brand"><i>✦</i> آفاق</div><div><button onclick="auth('login')">تسجيل الدخول</button></div></nav><main class="hero single"><div><div class="school-name">مدرسة بعيا للتعليم الأساسي والثانوي</div><h1>نصنع التميّز،<br>ونفتح آفاق <em>الإنجاز</em></h1><p>منصة المدرسة للميثاق والقيم الإيجابية والشراكة مع الأسرة والاحتفاء بقصص النجاح.</p><button class="primary" onclick="auth('signup')">إنشاء حساب</button></div></main><div class="public-nav">${['على خطى زايد','القيم الإيجابية','سفيرات الميثاق','الفصل الإيجابي','شراكة الأسرة','قصص النجاح'].map(x=>`<button onclick="publicPage('${x}')">${x}</button>`).join('')}</div></section>`}
async function loadHomeUpdates(){try{const r=await api('public/home');const box=document.querySelector('#homeUpdates');if(!box)return;box.innerHTML=`<h3>تحديثات آفاق</h3><div class="quick"><span class="bubble">✦</span><div><b>على خطى زايد: ${r.values.zayed_value}</b><small>قيمة هذا الشهر</small></div></div><div class="quick"><span class="bubble">♡</span><div><b>القيم الإيجابية: ${r.values.positive_value}</b><small>قيمة هذا الشهر</small></div></div><div class="quick"><span class="bubble">★</span><div><b>${r.counts.stories} قصص نجاح منشورة</b><small>${r.counts.ambassadors} سفيرات ميثاق معتمدات</small></div></div>`}catch{}}
function auth(mode){role='student';A().innerHTML=`<section class="auth"><div class="auth-card"><button class="back" onclick="landing()">← العودة للرئيسية</button><div class="brand" style="margin-top:17px"><i>✦</i> آفاق</div><h2>${mode==='signup'?'أنشئ حسابك':'أهلاً بعودتك'}</h2><p>${mode==='signup'?'اختَر نوع الحساب وأدخل بياناتك.':'سجّل دخولك بإيميلك وكلمة المرور.'}</p>${mode==='signup'?signupForm():loginForm()}<p style="text-align:center;margin-top:16px">${mode==='signup'?'لديك حساب؟':'ليس لديك حساب؟'} <button class="back" onclick="auth('${mode==='signup'?'login':'signup'}')">${mode==='signup'?'تسجيل الدخول':'إنشاء حساب'}</button></p></div></section>`}
function signupForm(){return `<div class="role-pick">${Object.entries(labels).map(([k,v])=>`<button class="${k==='student'?'active':''}" onclick="pickRole('${k}',this)">${v}</button>`).join('')}</div><form onsubmit="register(event)"><div class="grid"><div class="field"><label>الاسم الكامل</label><input name="name" required autocomplete="name"></div><div class="field"><label>البريد الإلكتروني</label><input name="email" type="email" required autocomplete="email"></div></div><div id="roleFields"><div class="grid"><div class="field"><label>الصف</label><select name="grade"><option>5</option><option>6</option><option>7</option></select></div><div class="field"><label>الشعبة</label><select name="section"><option>A</option><option>B</option><option>C</option></select></div></div></div><div class="field"><label>كلمة المرور</label><input name="password" type="password" minlength="6" required autocomplete="new-password"></div><button class="primary full">إنشاء الحساب</button></form>`}
function loginForm(){const last=localStorage.getItem('afaqLastEmail')||'';return `<form onsubmit="login(event)"><div class="field"><label>البريد الإلكتروني</label><input name="email" type="email" value="${last}" required autocomplete="username" list="emailChoices" oninput="suggestEmails(this.value)"><datalist id="emailChoices"></datalist></div><div class="field"><label>كلمة المرور</label><input name="password" type="password" required autocomplete="current-password"></div><button class="primary full" id="loginButton">تسجيل الدخول</button><p id="loginStatus" class="empty hidden"></p></form>`}
let emailTimer;function suggestEmails(prefix){clearTimeout(emailTimer);if(!prefix)return;emailTimer=setTimeout(async()=>{try{const users=await api('users?prefix='+encodeURIComponent(prefix));const list=document.querySelector('#emailChoices');if(list)list.innerHTML=users.map(x=>`<option value="${x.email}">${x.name} — ${labels[x.role]}</option>`).join('')}catch{}},250)}
function pickRole(r,el){role=r;document.querySelectorAll('.role-pick button').forEach(x=>x.classList.remove('active'));el.classList.add('active');const fields=document.querySelector('#roleFields');fields.innerHTML=['student','parent'].includes(r)?`<div class="grid"><div class="field"><label>الصف</label><select name="grade"><option>5</option><option>6</option><option>7</option></select></div><div class="field"><label>الشعبة</label><select name="section"><option>A</option><option>B</option><option>C</option></select></div></div>`:r==='teacher'?`<div class="field"><label>الوظيفة</label><select name="job"><option>معلم / معلمة</option><option>أخصائي / أخصائية اجتماعية</option></select></div>`:`<div class="notice">سيتم تفعيل صلاحيات هذا الحساب التجريبي مباشرة.</div>`}
async function register(e){e.preventDefault();const f=new FormData(e.target);try{const r=await api('auth/register',{name:f.get('name'),email:f.get('email'),password:f.get('password'),role,grade:f.get('grade')||'',section:f.get('section')||'',job:f.get('job')||''});user=r.user;role=user.role;dashboard()}catch(err){alert(err.message)}}
async function login(e){e.preventDefault();const f=new FormData(e.target),btn=document.querySelector('#loginButton'),msg=document.querySelector('#loginStatus');btn.disabled=true;btn.textContent='جارٍ الدخول…';msg.classList.remove('hidden');msg.textContent='يتم التحقق من الحساب…';try{const r=await api('auth/login',{email:f.get('email'),password:f.get('password')});user=r.user;role=user.role;localStorage.setItem('afaqLastEmail',user.email);dashboard()}catch(err){msg.textContent=err.message;btn.disabled=false;btn.textContent='تسجيل الدخول'}}
function dashboard(page='الرئيسية'){role=user.role;const n=nav[role];A().innerHTML=`<section class="dashboard"><aside class="side"><div class="brand"><i>✦</i> آفاق</div><div class="user"><div class="avatar">${user.name?.[0]||'م'}</div><div><b>${user.name||'مستخدم تجريبي'}</b><small>${labels[role]}</small></div></div><nav>${n.map(x=>`<button data-page="${x}" class="${x===page?'active':''}" onclick="dashboard('${x}')">${x}<i class="nav-dot hidden"></i></button>`).join('')}</nav><button class="logout" onclick="landing()">تسجيل الخروج</button></aside><main class="main"><header class="top"><div><p>مدرسة بعيا للتعليم الأساسي والثانوي</p><h2>${page==='الرئيسية'?'مرحبًا، '+(user.name||'بك')+' ✦':page}</h2></div><button class="lang" onclick="toggleLang()">العربية / EN</button></header><div id="view">${view(page)}</div></main></section>`;if(page==='الرئيسية')loadStats();if(role==='deputy')loadNotifications()}
function stats(){return `<div class="stats"><article class="stat" onclick="dashboard('تفاصيل المشاركات')" style="cursor:pointer"><span>المشاركات</span><b id="stat-participations">—</b><em>اضغطي للتفاصيل</em></article><article class="stat" onclick="dashboard('تفاصيل قصص النجاح')" style="cursor:pointer"><span>قصص النجاح</span><b id="stat-stories">—</b><em>اضغطي للتفاصيل</em></article><article class="stat" onclick="dashboard('تفاصيل قيد المراجعة')" style="cursor:pointer"><span>قيد المراجعة</span><b id="stat-pending">—</b><em>اضغطي للتفاصيل</em></article><article class="stat" onclick="dashboard('تفاصيل سفيرات الميثاق')" style="cursor:pointer"><span>سفيرات الميثاق</span><b id="stat-ambassadors">—</b><em>اضغطي للتفاصيل</em></article></div>`}
async function loadStats(){try{const [s,h]=await Promise.all([api('stats'),api('public/home')]);const put=(id,v)=>{const x=document.querySelector(id);if(x)x.textContent=v};put('#stat-participations',h.counts.participations);put('#stat-stories',h.counts.stories);put('#stat-pending',s.pending);put('#stat-ambassadors',h.counts.ambassadors)}catch{}}
async function loadNotifications(){try{const r=await api('review');const checks={'تقييم على خطى زايد':r.submissions.some(x=>x.kind.startsWith('على خطى زايد')&&x.status==='pending'),'تقييم القيم الإيجابية':r.submissions.some(x=>x.kind.startsWith('القيم الإيجابية')&&x.status==='pending'),'تقييم سفيرات الميثاق':r.submissions.some(x=>x.kind==='طلب سفيرة الميثاق'&&x.status==='pending'),'تقييم السلوك الإيجابي':r.submissions.some(x=>x.kind==='سلوك إيجابي'&&x.status==='pending'),'تقييم قصص النجاح':r.stories.some(x=>x.score===null)};Object.entries(checks).forEach(([page,on])=>{const dot=document.querySelector(`[data-page="${page}"] .nav-dot`);if(dot)dot.classList.toggle('hidden',!on)})}catch{}}
function view(p){if(p==='الرئيسية')return role==='director'?`<section class="card"><h3>مرحبًا بك في لوحة المدير</h3><p class="empty">يمكنك الاطلاع على جميع النتائج والتفاصيل من القائمة الجانبية.</p></section>`:`${stats()}<section class="card"><h3>عن آفاق</h3><p style="font-size:12px;line-height:2;color:var(--muted)">منصة تشجّع الالتزام والإنجاز والشراكة بين المدرسة والأسرة.</p></section>`;if(p.startsWith('تفاصيل '))return details(p.replace('تفاصيل ',''));if(p==='الميثاق')return charter();if(['على خطى زايد','القيم الإيجابية'].includes(p))return valueForm(p);if(p==='سفيرات الميثاق')return ambassador();if(p==='نتائجي')return studentResults();if(p==='إرسال سلوك إيجابي')return behaviorForm();if(p==='شراكة الأسرة')return storyForm('parent');if(p==='طلباتي السابقة')return parentRequests();if(p==='قيم الشهر')return monthlyValues();if(p.startsWith('تقييم '))return review(p.replace('تقييم ',''));if(p==='الفصل الإيجابي')return classScore();if(p==='شهاداتي')return certificate();if(p==='الإحصائيات'||p==='النتائج')return `${stats()}<section class="card"><h3>نتائج المنصة</h3></section>`;if(p==='المستخدمون')return `<section class="card"><h3>المستخدمون المسجلون</h3><p class="empty">تظهر الحسابات المسجلة عند ربط لوحة الإدارة النهائية.</p></section>`;return `<section class="card"><p class="empty">هذا القسم سيكون جاهزًا قريبًا.</p></section>`}
function details(type){loadDetails(type);return `<section class="card"><p class="empty">جارٍ تحميل التفاصيل…</p></section>`}
async function loadDetails(type){try{const [review,home]=await Promise.all([api('review'),api('public/home')]);let items=[];if(type==='المشاركات')items=review.submissions.filter(x=>x.kind!=='طلب سفيرة الميثاق');else if(type==='قصص النجاح')items=home.stories;else if(type==='قيد المراجعة')items=[...review.submissions.filter(x=>x.status==='pending'),...review.stories.filter(x=>x.score===null)];else items=home.ambassadors;const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<section class="card"><h3>${type}</h3>${items.length?items.map(x=>`<div class="item"><span class="bubble">✦</span><div><b>${x.student}</b><small>${x.kind||x.text||'مشاركة معتمدة'}</small></div></div>`).join(''):'<p class="empty">لا توجد بيانات بعد.</p>'}</section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
function recent(){const all=[...data.submissions,...data.stories,...data.behaviors].slice(-4).reverse();return all.length?all.map(x=>`<div class="item"><span class="bubble">✦</span><div><b>${x.title||x.student}</b><small>${x.type||'طلب جديد'}</small></div><span class="pill ${x.score?'good':''}">${x.score?x.score+'/5':'بانتظار'}</span></div>`).join(''):'<p class="empty">لا توجد طلبات بعد.</p>'}
function charter(){return `<section class="card"><h3>ميثاق الطالب</h3><p style="line-height:2.2;font-size:14px">أنا <b>${user.name||'[اسم الطالب]'}</b> أتعهد بأن أحترم قوانين مدرسة بعيا للتعليم الأساسي والثانوي، وأن ألتزم بالقيم الإيجابية، وأكون قدوة حسنة في سلوكي وتعاملي.</p><label class="check"><input type="checkbox" id="agree"> أوافق وأؤكد تعهّدي بالميثاق.</label><button class="primary" onclick="issueCharter()">تأكيد التوقيع وإصدار الشهادة</button></section>`}
function issueCharter(){if(!document.querySelector('#agree').checked)return alert('ضعي إشارة صح للموافقة على الميثاق.');alert('تم إصدار شهادة شكر وتقدير وإرسالها إلى إيميلك (تجريبيًا).');dashboard('شهاداتي')}
function valueForm(type){loadValueForm(type);return `<section class="card"><p class="empty">جارٍ تحميل قيمة هذا الشهر…</p></section>`}
async function loadValueForm(type){try{const settings=await api('settings');const value=type==='على خطى زايد'?settings.zayed_value:settings.positive_value;const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<div class="notice">قيمة هذا الشهر: <b>${value}</b> — ارفعي دليلًا واحدًا فقط. يحصل الطالب فورًا على شهادة شكر للمشاركة.</div><section class="card"><h3>${type}</h3><form onsubmit="submitValue(event,'${type}: ${value}')"><div class="field"><label>اكتبي وصف مشاركتك</label><textarea name="text" required placeholder="كيف طبقتِ القيمة؟"></textarea></div><div class="field"><label>الدليل: صورة أو فيديو حتى 100 MB</label><input name="proof" type="file" accept="image/*,video/*"></div><button class="primary">إرسال الدليل والحصول على الشهادة</button></form></section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
async function submitValue(e,type){e.preventDefault();const f=new FormData(e.target);try{await api('submissions',{student:user.name,grade:user.grade,section:user.section,kind:type,text:f.get('text'),file:await asFile(e.target.proof)});alert('تم حفظ الدليل والنص في قاعدة البيانات. وصلت شهادة شكر لمشاركتك إلى إيميلك (تجريبيًا).');dashboard('شهاداتي')}catch(err){alert(err.message)}}
function ambassador(){return `<section class="card"><h3>طلب سفيرة الميثاق</h3><p class="notice">ارسلي طلبك ليصل مباشرة إلى نائب المدير للمراجعة.</p><form onsubmit="submitAmbassador(event)"><div class="field"><label>لماذا ترغبين أن تكوني سفيرة للميثاق؟</label><textarea name="text" required></textarea></div><button class="primary">إرسال الطلب</button></form></section>`}
async function submitAmbassador(e){e.preventDefault();try{await api('submissions',{student:user.name,grade:user.grade,section:user.section,kind:'طلب سفيرة الميثاق',text:new FormData(e.target).get('text')});alert('تم حفظ الطلب وإرساله إلى نائب المدير.');dashboard()}catch(err){alert(err.message)}}
function storyForm(kind){const label=kind==='teacher'?'إنجاز طالب':'قصة نجاح من ولي الأمر';return `<section class="card"><h3>${label}</h3><p class="notice">تصل القصة إلى نائب المدير للتقييم والقرار بالنشر. تصل لك شهادة شكر فور الإرسال.</p><form onsubmit="submitStory(event,'${kind}')"><div class="grid"><div class="field"><label>اسم الطالب</label><input name="student" required></div><div class="field"><label>الصف والشعبة</label><input name="class" placeholder="مثال: 5A" required></div></div><div class="field"><label>القصة أو الإنجاز</label><textarea name="text" required></textarea></div><div class="field"><label>صورة أو فيديو اختياري</label><input name="proof" type="file" accept="image/*,video/*"></div><button class="primary">إرسال القصة</button></form></section>`}
async function submitStory(e,kind){e.preventDefault();const f=new FormData(e.target);const cl=f.get('class').trim();try{await api('stories',{student:f.get('student'),grade:cl[0]||'',section:cl.slice(-1)||'',author:user.name,source_role:kind,text:f.get('text'),file:await asFile(e.target.proof)});alert('تم حفظ القصة والدليل وإرسالها إلى نائب المدير. وشهادة الشكر أرسلت إلى إيميلك (تجريبيًا).');dashboard('طلباتي السابقة')}catch(err){alert(err.message)}}
function parentRequests(){loadParentRequests();return `<section class="card"><p class="empty">جارٍ تحميل طلباتك السابقة…</p></section>`}
async function loadParentRequests(){try{const items=await api('parent-requests?author='+encodeURIComponent(user.name));const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<section class="card"><h3>طلباتي السابقة</h3>${items.length?items.map(x=>`<div class="item"><span class="bubble">♡</span><div><b>${x.student}</b><small>${x.text}</small></div><span class="pill ${x.published?'good':''}">${x.published?'تم الاعتماد والنشر':x.score===null?'بانتظار قرار نائب المدير':x.score+' / 5'}</span></div>`).join(''):'<p class="empty">لم ترسلي أي قصة بعد.</p>'}</section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
function behaviorForm(){return `<section class="card"><h3>ترشيح سلوك إيجابي</h3><form onsubmit="submitBehavior(event)"><div class="grid"><div class="field"><label>اسم الطالب</label><input name="student" required></div><div class="field"><label>الصف والشعبة</label><input name="class" placeholder="مثال: 6B" required></div></div><div class="field"><label>سبب الترشيح</label><textarea name="text" placeholder="مثل: حضور ممتاز أو تفوق أكاديمي" required></textarea></div><button class="primary">إرسال لنائب المدير</button></form></section>`}
async function submitBehavior(e){e.preventDefault();const f=new FormData(e.target);const cl=f.get('class').trim();try{await api('submissions',{student:f.get('student'),grade:cl[0]||'',section:cl.slice(-1)||'',kind:'سلوك إيجابي',text:f.get('text')});alert('تم حفظ الترشيح وإرساله إلى نائب المدير.');dashboard()}catch(err){alert(err.message)}}
function monthlyValues(){loadMonthlyValues();return `<section class="card"><p class="empty">جارٍ تحميل القيم الحالية…</p></section>`}
async function loadMonthlyValues(){try{const s=await api('settings');const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<section class="card"><h3>تحديد قيم الشهر</h3><form onsubmit="saveValues(event)"><div class="field"><label>على خطى زايد</label><input name="zayed" value="${s.zayed_value}" required></div><div class="field"><label>القيم الإيجابية</label><input name="positive" value="${s.positive_value}" required></div><button class="primary">حفظ وإرسال للطلاب</button></form></section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
async function saveValues(e){e.preventDefault();const f=new FormData(e.target);try{await api('settings',{zayed_value:f.get('zayed'),positive_value:f.get('positive')});alert('تم حفظ قيم الشهر وإتاحتها للطلاب.')}catch(err){alert(err.message)}}
function review(section){loadReview(section);return `<section class="card"><h3>تقييم ${section}</h3><p class="empty">جارٍ تحميل النصوص والأدلة من قاعدة البيانات…</p></section>`}
function matchesSection(x,section){if(section==='على خطى زايد')return x.kind?.startsWith('على خطى زايد');if(section==='القيم الإيجابية')return x.kind?.startsWith('القيم الإيجابية');if(section==='سفيرات الميثاق')return x.kind==='طلب سفيرة الميثاق';if(section==='السلوك الإيجابي')return x.kind==='سلوك إيجابي';if(section==='قصص النجاح')return x.kind2==='story';return false}
async function loadReview(section){try{const r=await api('review');const items=[...r.submissions.map(x=>({...x,kind2:'submission'})),...r.stories.map(x=>({...x,kind2:'story'}))].filter(x=>matchesSection(x,section));const box=document.querySelector('#view');if(!box)return;const isDecision=['سفيرات الميثاق','السلوك الإيجابي'].includes(section);const rows=items.map(x=>{const decision=isDecision?`<select id="decision-${x.id}"><option value="">اختاري القرار</option><option value="accepted" ${x.status==='accepted'?'selected':''}>قبول</option><option value="rejected" ${x.status==='rejected'?'selected':''}>رفض</option></select>`:`<select id="score-${x.kind2}-${x.id}"><option value="">اختاري</option>${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${x.score===n?'selected':''}>${n} / 5</option>`).join('')}</select>${x.kind2==='story'?`<label class="check"><input type="checkbox" id="publish-${x.id}" ${x.published?'checked':''}> اعتماد ونشر القصة</label>`:''}`;return `<tr><td><b>${x.student}</b><br><small>${x.grade||''}${x.section||''}</small></td><td><b>${x.kind||'قصة نجاح'}</b><br><small>${x.text}</small></td><td>${x.file_url?`<a href="${x.file_url}" target="_blank">عرض ${x.file_name||'الدليل'}</a>`:'لا يوجد'}</td><td>${decision}</td><td><button class="outline" onclick="scoreItem(${x.id},'${x.kind2}','${section}')">${isDecision?'حفظ القرار':'حفظ التقييم'}</button></td></tr>`}).join('');box.innerHTML=`<section class="card"><h3>تقييم ${section}</h3>${items.length?`<table class="table"><thead><tr><th>الطالب</th><th>النوع والنص</th><th>الدليل</th><th>${isDecision?'القرار':'الدرجة'}</th><th>الحفظ</th></tr></thead><tbody>${rows}</tbody></table>`:'<p class="empty">لا توجد طلبات في هذه البوابة.</p>'}</section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
async function scoreItem(id,type,section){try{if(['سفيرات الميثاق','السلوك الإيجابي'].includes(section)){const status=document.querySelector('#decision-'+id)?.value;if(!status)return alert('اختاري قبول أو رفض أولًا.');await api(section==='سفيرات الميثاق'?'review/ambassador':'review/behavior',{id,status});alert(status==='accepted'?(section==='السلوك الإيجابي'?'تم اعتماد السلوك ونشره في قصص النجاح.':'تم قبول الطلب. ظهر اسم الطالبة في سفيرات الميثاق وحسابها.'):'تم رفض الطلب.');return dashboard('تقييم '+section)}const field=document.querySelector('#score-'+type+'-'+id);const s=field?.value;if(s===''||s===undefined)return alert('اختاري درجة من 0 إلى 5 أولًا.');await api(type==='story'?'review/story':'review/submission',{id,score:+s,published:type==='story'&&document.querySelector('#publish-'+id).checked});alert('تم حفظ التقييم، وستظهر النتيجة تلقائيًا في حساب الطالب.');dashboard('تقييم '+section)}catch(err){alert(err.message)}}
function studentResults(){loadStudentResults();return `<section class="card"><p class="empty">جارٍ تحميل نتائجك…</p></section>`}
async function loadStudentResults(){try{const r=await api('student-activity?student='+encodeURIComponent(user.name));const items=[...r.submissions,...r.stories];const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<section class="card"><h3>نتائجي وتقييماتي</h3>${items.length?items.map(x=>{const ambassador=x.kind==='طلب سفيرة الميثاق';const result=ambassador?(x.status==='accepted'?'تم قبولك سفيرة للميثاق ✦':x.status==='rejected'?'لم يتم القبول':'بانتظار قرار نائب المدير'):(x.score===null?'بانتظار تقييم نائب المدير':x.score+' / 5');return `<div class="item"><span class="bubble">✦</span><div><b>${x.kind||'قصة نجاح'}</b><small>${x.text}</small></div><span class="pill ${(x.score!==null||x.status==='accepted')?'good':''}">${result}</span></div>`}).join(''):'<p class="empty">لم ترسلي أي مشاركة بعد.</p>'}</section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
function classScore(){loadClassWinners();return `<section class="card"><p class="empty">جارٍ تحميل الشعب الفائزة…</p></section>`}
async function loadClassWinners(){try{const winners=await api('class-winners');const picked=Object.fromEntries(winners.map(x=>[x.grade,x.section]));const radio=grade=>['A','B','C'].map(s=>`<label class="outline" style="display:inline-flex;gap:6px;margin-left:7px;align-items:center"><input type="radio" name="grade-${grade}" value="${s}" ${picked[grade]===s?'checked':''}> الشعبة ${s}</label>`).join('');const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<section class="card"><h3>الفصل الإيجابي</h3><p class="notice">اختاري شعبة فائزة واحدة من كل صف.</p><form onsubmit="saveClassWinners(event)">${['5','6','7'].map(g=>`<div class="field"><label style="font-size:16px">الصف ${g}</label><div>${radio(g)}</div></div>`).join('')}<button class="primary">حفظ الشعب الفائزة</button></form></section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
async function saveClassWinners(e){e.preventDefault();const values={};for(const grade of ['5','6','7']){const choice=document.querySelector(`input[name="grade-${grade}"]:checked`);if(!choice)return alert('اختاري شعبة فائزة للصف '+grade);values[grade]=choice.value}try{await api('class-winners',values);alert('تم حفظ الشعب الفائزة.');dashboard('الفصل الإيجابي')}catch(err){alert(err.message)}}
function stories(){const list=data.stories;return `<section class="card"><div class="card-title"><h3>قصص النجاح</h3>${role==='deputy'?'<button class="outline" onclick="publishAll()">نشر المحدد</button>':''}</div>${list.length?list.map((x,i)=>`<div class="item"><span class="bubble">★</span><div><b>${x.student}</b><small>${x.text}</small></div><span class="pill ${x.published?'good':''}">${x.published?'منشورة':'قيد المراجعة'}</span>${role==='deputy'?`<button class="outline" onclick="publishStory(${i})">${x.published?'إلغاء':'نشر'}</button>`:''}</div>`).join(''):'<p class="empty">لا توجد قصص بعد.</p>'}</section>`}
function publishStory(i){alert('النشر أصبح جزءًا من شاشة المراجعة والتقييم عند نائب المدير.')}
function publishAll(){alert('اختاري كل قصة على حدة للنشر.')}
function certificate(){return `<div class="certificate"><div class="brand"><i>✦</i> آفاق</div><h2>شهادة شكر وتقدير</h2><p>تتقدم مدرسة بعيا للتعليم الأساسي والثانوي بالشكر والتقدير إلى</p><h2>${user.name||'اسم المستخدم'}</h2><p>تقديرًا لمشاركته الفاعلة والتزامه بالقيم الإيجابية.</p><button class="primary" onclick="alert('تم تنزيل الشهادة كصورة في النسخة النهائية.')">تنزيل الشهادة</button></div>`}
function publicPage(name){A().innerHTML=`<section class="public"><header><div class="brand"><i>✦</i> آفاق</div><button class="outline" onclick="landing()">الرئيسية</button></header><main><div class="eyebrow">مدرسة بعيا للتعليم الأساسي والثانوي</div><h1>${name}</h1><div id="publicContent"><p class="empty">جارٍ تحميل البيانات المعتمدة…</p></div></main></section>`;loadPublicPage(name)}
async function loadPublicPage(name){try{const h=await api('public/home');const box=document.querySelector('#publicContent');if(!box)return;if(name==='سفيرات الميثاق'){box.innerHTML=h.ambassadors.length?h.ambassadors.map(x=>`<article class="story"><b>✦ ${x.student}</b><small>سفيرة الميثاق · الصف ${x.grade}${x.section}</small></article>`).join(''):'<p class="empty">لا توجد سفيرات ميثاق معتمدات بعد.</p>'}else if(name==='قصص النجاح'){box.innerHTML=h.stories.length?h.stories.map(x=>`<article class="story"><b>${x.student}</b><small>سلوك إيجابي معتمد · ${x.grade}${x.section}</small><p>${x.text}</p>${x.file_url?`<a href="${x.file_url}" target="_blank">عرض الدليل المرفق</a>`:''}</article>`).join(''):'<p class="empty">سيتم نشر السلوكيات الإيجابية المعتمدة هنا.</p>'}else if(name==='شراكة الأسرة'){box.innerHTML=h.family_stories.length?h.family_stories.map(x=>`<article class="story"><b>${x.student}</b><small>قصة من وليّ الأمر · ${x.grade}${x.section}</small><p>${x.text}</p>${x.file_url?`<a href="${x.file_url}" target="_blank">عرض الدليل المرفق</a>`:''}</article>`).join(''):'<p class="empty">سيتم نشر قصص الأسرة المعتمدة هنا.</p>'}else if(name==='على خطى زايد'){box.innerHTML=`<section class="card"><h3>قيمة هذا الأسبوع</h3><p class="notice">${h.values.zayed_value}</p><h3 style="margin-top:22px">قيم نعتز بها</h3><div class="action-grid">${['المسؤولية','الاحترام','التعاون','الانتماء','التسامح','المواطنة الصالحة'].map(x=>`<div class="action"><span class="bubble">✦</span><b>${x}</b></div>`).join('')}</div></section>`}else if(name==='القيم الإيجابية'){box.innerHTML=`<section class="card"><h3>القيمة الإيجابية لهذا الأسبوع</h3><p class="notice">${h.values.positive_value}</p><div class="action-grid">${['المساعدة','الصدق','الاحترام','التعاون','الإيثار','اللطف'].map(x=>`<div class="action"><span class="bubble">♡</span><b>${x}</b></div>`).join('')}</div></section>`}else{box.innerHTML=`<section class="card"><p class="empty">تظهر هنا المعلومات والنتائج المعتمدة الخاصة بقسم «${name}».</p></section>`}}catch(err){document.querySelector('#publicContent').innerHTML=`<p class="empty">${err.message}</p>`}}
function toggleLang(){document.documentElement.lang=document.documentElement.lang==='ar'?'en':'ar';document.documentElement.dir=document.documentElement.dir==='rtl'?'ltr':'rtl';alert('تم تغيير اتجاه الصفحة تجريبيًا. الترجمة الإنجليزية الكاملة ستضاف في مرحلة النصوص.')}
/* الإصدار 8: نتائج الفصل الإيجابي العامة وصلاحيات التفاصيل */
function stats(){const canSeeDetails=['director','deputy'].includes(role);const card=(label,id,page)=>`<article class="stat" ${canSeeDetails?`onclick="dashboard('تفاصيل ${page}')" style="cursor:pointer"`:''}><span>${label}</span><b id="${id}">—</b>${canSeeDetails?'<em>اضغطي للتفاصيل</em>':''}</article>`;return `<div class="stats">${card('المشاركات','stat-participations','المشاركات')}${card('قصص النجاح','stat-stories','قصص النجاح')}${card('قيد المراجعة','stat-pending','قيد المراجعة')}${card('سفيرات الميثاق','stat-ambassadors','سفيرات الميثاق')}</div>`}
function details(type){if(!['director','deputy'].includes(role))return `<section class="card"><p class="empty">هذه التفاصيل متاحة للمدير ونائب المدير فقط.</p></section>`;loadDetails(type);return `<section class="card"><p class="empty">جارٍ تحميل التفاصيل…</p></section>`}
async function loadPublicPage(name){try{const h=await api('public/home');const box=document.querySelector('#publicContent');if(!box)return;if(name==='سفيرات الميثاق'){box.innerHTML=h.ambassadors.length?h.ambassadors.map(x=>`<article class="story"><b>✦ ${x.student}</b><small>سفيرة الميثاق · الصف ${x.grade}${x.section}</small></article>`).join(''):'<p class="empty">لا توجد سفيرات ميثاق معتمدات بعد.</p>'}else if(name==='قصص النجاح'){box.innerHTML=h.stories.length?h.stories.map(x=>`<article class="story"><b>${x.student}</b><small>سلوك إيجابي معتمد · ${x.grade}${x.section}</small><p>${x.text}</p>${x.file_url?`<a href="${x.file_url}" target="_blank">عرض الدليل المرفق</a>`:''}</article>`).join(''):'<p class="empty">سيتم نشر السلوكيات الإيجابية المعتمدة هنا.</p>'}else if(name==='شراكة الأسرة'){box.innerHTML=h.family_stories.length?h.family_stories.map(x=>`<article class="story"><b>${x.student}</b><small>قصة من وليّ الأمر · ${x.grade}${x.section}</small><p>${x.text}</p>${x.file_url?`<a href="${x.file_url}" target="_blank">عرض الدليل المرفق</a>`:''}</article>`).join(''):'<p class="empty">سيتم نشر قصص الأسرة المعتمدة هنا.</p>'}else if(name==='الفصل الإيجابي'){const winners=Object.fromEntries((h.class_winners||[]).map(x=>[x.grade,x.section]));box.innerHTML=`<section class="card"><h3>الفصل الإيجابي</h3>${['5','6','7'].map(g=>winners[g]?`<article class="story"><b>الصف ${g}</b><p>الشعبة الفائزة: <strong>${winners[g]}</strong></p></article>`:`<article class="story"><b>الصف ${g}</b><p class="empty">لم تُعتمد الشعبة الفائزة بعد.</p></article>`).join('')}</section>`}else if(name==='على خطى زايد'){box.innerHTML=`<section class="card"><h3>قيمة هذا الأسبوع</h3><p class="notice">${h.values.zayed_value}</p><h3 style="margin-top:22px">قيم نعتز بها</h3><div class="action-grid">${['المسؤولية','الاحترام','التعاون','الانتماء','التسامح','المواطنة الصالحة'].map(x=>`<div class="action"><span class="bubble">✦</span><b>${x}</b></div>`).join('')}</div></section>`}else if(name==='القيم الإيجابية'){box.innerHTML=`<section class="card"><h3>القيمة الإيجابية لهذا الأسبوع</h3><p class="notice">${h.values.positive_value}</p><div class="action-grid">${['المساعدة','الصدق','الاحترام','التعاون','الإيثار','اللطف'].map(x=>`<div class="action"><span class="bubble">♡</span><b>${x}</b></div>`).join('')}</div></section>`}else{box.innerHTML=`<section class="card"><p class="empty">تظهر هنا المعلومات والنتائج المعتمدة الخاصة بقسم «${name}».</p></section>`}}catch(err){document.querySelector('#publicContent').innerHTML=`<p class="empty">${err.message}</p>`}}
const afaqBaseView=view;
view=(page)=>page==='الإحصائيات والنتائج'?stats():afaqBaseView(page);
const afaqBaseDashboard=dashboard;
dashboard=(page='الرئيسية')=>{afaqBaseDashboard(page);if(page==='الإحصائيات والنتائج')loadStats()};

issueCharter=async()=>{if(!document.querySelector('#agree').checked)return alert('ضعي إشارة صح للموافقة على الميثاق.');try{await api('certificates',{owner_email:user.email,owner_name:user.name,title:'شهادة الالتزام بالميثاق',detail:'تقديرًا لتعهّدك بالالتزام بميثاق المدرسة.'});alert('تم إصدار شهادة الالتزام. ستجدينها في قسم شهاداتي.');dashboard('شهاداتي')}catch(err){alert(err.message)}};

loadValueForm=async(type)=>{try{const [settings,activity]=await Promise.all([api('settings'),api('student-activity?student='+encodeURIComponent(user.name))]);const value=type==='على خطى زايد'?settings.zayed_value:settings.positive_value;const kind=`${type}: ${value}`;const sent=activity.submissions.some(x=>x.kind===kind&&x.owner_email===user.email);const box=document.querySelector('#view');if(!box)return;if(sent){box.innerHTML=`<section class="card"><h3>${type}</h3><p class="notice">قيمة هذا الشهر: <b>${value}</b></p><p class="empty">أرسلتِ دليلك لهذه القيمة بالفعل. عند تحديد نائب المدير قيمة جديدة ستتمكنين من المشاركة مرة أخرى.</p></section>`;return}box.innerHTML=`<div class="notice">قيمة هذا الشهر: <b>${value}</b> — ارفعي دليلًا واحدًا فقط. تحصلين فورًا على شهادة شكر للمشاركة.</div><section class="card"><h3>${type}</h3><form onsubmit="submitValue(event,'${kind}')"><div class="field"><label>اكتبي وصف مشاركتك</label><textarea name="text" required placeholder="كيف طبقتِ القيمة؟"></textarea></div><div class="field"><label>الدليل: صورة أو فيديو حتى 100 MB</label><input name="proof" type="file" accept="image/*,video/*"></div><button class="primary">إرسال الدليل والحصول على الشهادة</button></form></section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}};

submitValue=async(e,kind)=>{e.preventDefault();const f=new FormData(e.target);try{await api('submissions',{student:user.name,grade:user.grade,section:user.section,owner_email:user.email,kind,text:f.get('text'),file:await asFile(e.target.proof)});const value=kind.split(': ').slice(1).join(': ');await api('certificates',{owner_email:user.email,owner_name:user.name,title:'شهادة شكر وتقدير',detail:`تقديرًا لمشاركتك في قيمة «${value}».`});alert('تم حفظ الدليل وإصدار شهادة الشكر.');dashboard('شهاداتي')}catch(err){alert(err.message)}};

certificate=()=>{loadCertificates();return '<section class="card"><p class="empty">جارٍ تحميل شهاداتك…</p></section>'};
async function loadCertificates(){try{const list=await api('certificates?email='+encodeURIComponent(user.email));window.afaqCertificates=list;const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<section class="card"><h3>شهاداتي</h3>${list.length?list.map((c,i)=>`<div class="item"><span class="bubble">✦</span><div><b>${c.title}</b><small>${c.detail}</small></div><button class="outline" onclick="downloadCertificate(${i})">تنزيل الشهادة</button></div>`).join(''):'<p class="empty">لم تحصلي على شهادات بعد.</p>'}</section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}
function downloadCertificate(i){const c=window.afaqCertificates?.[i];if(!c)return;const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1000;const x=canvas.getContext('2d');x.fillStyle='#fffdf8';x.fillRect(0,0,1600,1000);x.strokeStyle='#6d4dd8';x.lineWidth=18;x.strokeRect(45,45,1510,910);x.fillStyle='#201b3c';x.textAlign='center';x.font='bold 62px Arial';x.fillText('✦ آفاق',800,190);x.font='bold 64px Arial';x.fillText(c.title,800,360);x.font='34px Arial';x.fillText('تتقدم مدرسة بعيا للتعليم الأساسي والثانوي بالشكر والتقدير إلى',800,470);x.font='bold 56px Arial';x.fillText(c.owner_name,800,565);x.font='32px Arial';x.fillText(c.detail,800,670);x.font='26px Arial';x.fillText('مع تمنياتنا بمزيد من التميّز والنجاح',800,805);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=canvas.toDataURL('image/png');a.click()}

/* الهوية البصرية الرسمية لمدرسة بعيا */
document.head.insertAdjacentHTML('beforeend',`<style id="afaq-school-identity">
:root{--navy:#102b46;--navy-2:#193a5a;--gold:#caa04b;--paper:#f7f6f1;--ink:#132c45}
body{background:var(--paper);color:var(--ink)}
.moe-logo{width:132px;height:112px;object-fit:contain;mix-blend-mode:multiply;display:block;margin:0 auto 12px}
.landing.official{background:linear-gradient(135deg,#faf9f5 0%,#eef0ed 60%,#e9e6d8 100%);min-height:100vh}.landing.official .nav{border-bottom:1px solid #ded8c7;background:#fffdf9}.landing.official .brand,.student-portal .brand{color:var(--navy)}.landing.official .brand i{color:var(--gold)}
.official-hero{max-width:960px;margin:36px auto 32px;padding:50px 55px;text-align:center;background:rgba(255,255,255,.76);border:1px solid #e3ddcd;border-radius:28px;box-shadow:0 22px 54px rgba(16,43,70,.10)}.school-official-name{font-size:24px;font-weight:900;color:var(--navy);letter-spacing:.1px;margin:8px 0}.official-hero h1{color:var(--navy);font-size:52px;line-height:1.18;margin:17px 0}.official-hero h1 em{color:var(--gold);font-style:normal}.official-hero p{max-width:660px;margin:0 auto 24px;color:#5a6978;font-size:16px;line-height:2}.official-hero .primary{background:var(--navy);box-shadow:0 12px 20px rgba(16,43,70,.2)}.official-hero .primary:hover{background:var(--navy-2)}
.student-portal{background:var(--paper)}.student-portal .side{background:linear-gradient(180deg,var(--navy),#0d2035);box-shadow:0 0 28px rgba(16,43,70,.16)}.student-portal .side .brand,.student-portal .side .user b{color:#fff}.student-portal .side .user small{color:#d3dbe4}.student-portal .side nav button{color:#d8e0e8}.student-portal .side nav button.active,.student-portal .side nav button:hover{background:rgba(202,160,75,.18);color:#fff;border-right:3px solid var(--gold)}.student-portal .main{background:linear-gradient(135deg,#f7f6f1,#eff1ef)}.student-portal .top{border-bottom:1px solid #deded7}.student-portal .top p{color:var(--gold);font-weight:800}.student-portal .top h2{color:var(--navy)}.student-portal .card,.student-portal .stat{border:1px solid #e4e1d8;box-shadow:0 10px 28px rgba(16,43,70,.07);background:#fffefd}.student-portal .stat b{color:var(--navy)}.student-portal .primary{background:var(--navy)}.student-portal .notice{border-right:4px solid var(--gold);background:#faf6e8;color:var(--navy)}
.student-welcome{display:flex;align-items:center;gap:18px;padding:22px 25px;margin-bottom:18px;border-radius:18px;background:linear-gradient(115deg,var(--navy),var(--navy-2));color:#fff;box-shadow:0 13px 27px rgba(16,43,70,.18)}.student-welcome .seal{width:54px;height:54px;border-radius:50%;background:var(--gold);color:var(--navy);display:grid;place-items:center;font-size:24px;font-weight:900}.student-welcome b{font-size:20px}.student-welcome small{color:#e4e8ed;display:block;margin-top:4px}
.certificate-list-logo{width:92px;height:74px;object-fit:contain;mix-blend-mode:multiply;margin-bottom:7px}.certificate-card-head{display:flex;align-items:center;gap:12px;border-bottom:1px solid #e7e1d3;padding-bottom:12px;margin-bottom:8px}.certificate-card-head b{color:var(--navy)}
</style>`);

landing=()=>{A().innerHTML=`<section class="landing official"><nav class="nav"><div class="brand"><i>✦</i> آفاق</div><button onclick="auth('login')">تسجيل الدخول</button></nav><main class="official-hero"><img src="/assets/ministry-logo.png" class="moe-logo" alt="شعار وزارة التربية والتعليم"><div class="school-official-name">مدرسة بعيا للتعليم الأساسي والثانوي</div><h1>نصنع التميّز<br><em>ونفتح آفاق الإنجاز</em></h1><p>منصة مدرسية رسمية للميثاق والقيم الإيجابية والشراكة مع الأسرة والاحتفاء بالإنجاز.</p><button class="primary" onclick="auth('signup')">إنشاء حساب</button></main><div class="public-nav">${['على خطى زايد','القيم الإيجابية','سفيرات الميثاق','الفصل الإيجابي','شراكة الأسرة','قصص النجاح'].map(x=>`<button onclick="publicPage('${x}')">${x}</button>`).join('')}</div></section>`};

const afaqDashboardWithStats=dashboard;
dashboard=(page='الرئيسية')=>{afaqDashboardWithStats(page);const portal=document.querySelector('.dashboard');portal?.classList.add('afaq-portal',`role-${role}`);if(role!=='student')return;portal?.classList.add('student-portal');const viewBox=document.querySelector('#view');if(page==='الرئيسية'&&viewBox)viewBox.insertAdjacentHTML('afterbegin',`<section class="student-welcome"><div class="seal">✦</div><div><b>بوابة الطالب</b><small>مدرسة بعيا للتعليم الأساسي والثانوي · مسارك نحو التميّز</small></div></section>`) };

submitValue=async(e,kind)=>{e.preventDefault();const f=new FormData(e.target);try{await api('submissions',{student:user.name,grade:user.grade,section:user.section,owner_email:user.email,kind,text:f.get('text'),file:await asFile(e.target.proof)});const value=kind.split(': ').slice(1).join(': ');await api('certificates',{owner_email:user.email,owner_name:user.name,title:'شهادة شكر وتقدير',detail:`تقديرًا لمشاركتك في قيمة [${value}].`});alert('تم حفظ الدليل وإصدار شهادة الشكر.');dashboard('شهاداتي')}catch(err){alert(err.message)}};

async function loadCertificates(){try{const list=await api('certificates?email='+encodeURIComponent(user.email));window.afaqCertificates=list;const box=document.querySelector('#view');if(!box)return;box.innerHTML=`<section class="card"><div class="certificate-card-head"><img src="/assets/ministry-logo.png" class="certificate-list-logo" alt="شعار الوزارة"><div><h3>شهاداتي</h3><small>سجل شهادات الطالب الرسمية</small></div></div>${list.length?list.map((c,i)=>`<div class="item"><span class="bubble">✦</span><div><b>${c.title}</b><small>${c.detail}</small></div><button class="outline" onclick="downloadCertificate(${i})">تنزيل الشهادة</button></div>`).join(''):'<p class="empty">لم تحصلي على شهادات بعد.</p>'}</section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}}

downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1000;const x=canvas.getContext('2d');x.fillStyle='#fcfbf6';x.fillRect(0,0,1600,1000);x.fillStyle='#102b46';x.fillRect(0,0,1600,95);x.strokeStyle='#caa04b';x.lineWidth=14;x.strokeRect(45,45,1510,910);const logo=new Image();logo.src='/assets/ministry-logo.png';await new Promise(resolve=>{logo.onload=resolve;logo.onerror=resolve});if(logo.complete&&logo.naturalWidth)x.drawImage(logo,665,102,270,150);x.fillStyle='#102b46';x.textAlign='center';x.font='bold 57px Arial';x.fillText('شهادة شكر وتقدير',800,335);x.fillStyle='#caa04b';x.fillRect(615,365,370,4);x.fillStyle='#132c45';x.font='31px Arial';x.fillText('تتقدم مدرسة بعيا للتعليم الأساسي والثانوي بالشكر والتقدير إلى',800,450);x.font='bold 58px Arial';x.fillText(c.owner_name,800,545);x.font='32px Arial';x.fillText(c.detail,800,640);x.textAlign='right';x.font='bold 28px Arial';x.fillText('مديرة المدرسة',1390,805);x.font='32px Arial';x.fillText('يلوى المنصوري',1390,850);x.textAlign='left';x.font='27px Arial';x.fillText('مدرسة بعيا للتعليم الأساسي والثانوي',205,850);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=canvas.toDataURL('image/png');a.click()};

document.head.insertAdjacentHTML('beforeend',`<style id="afaq-global-professional-theme">
/* نظام موحّد لكل لوحات آفاق: 60% أوف وايت، 30% كحلي، 10% ذهبي */
.afaq-portal{background:#f5f4ef;min-height:100vh}.afaq-portal .side{background:linear-gradient(180deg,#102b46,#0b2036);border:0;box-shadow:0 0 32px rgba(16,43,70,.20)}.afaq-portal .side .brand,.afaq-portal .side .user b{color:#fff}.afaq-portal .side .brand i{color:#caa04b}.afaq-portal .side .user{border-color:rgba(255,255,255,.14)}.afaq-portal .side .user small{color:#cfdae3}.afaq-portal .side .avatar{background:linear-gradient(135deg,#d9b968,#b78931);color:#102b46}.afaq-portal .side nav button{color:#dbe4eb;padding:12px 11px;border-radius:10px}.afaq-portal .side nav button.active,.afaq-portal .side nav button:hover{background:rgba(202,160,75,.18);color:#fff;border-right:3px solid #caa04b}.afaq-portal .logout{color:#efb0ae}.afaq-portal .main{background:linear-gradient(135deg,#f8f7f2,#eff1f0);padding:34px 6%}.afaq-portal .top{border-bottom:1px solid #deded5;padding-bottom:18px;margin-bottom:26px}.afaq-portal .top p{color:#a47c2f;font-size:12px;font-weight:800}.afaq-portal .top h2{color:#102b46;font-size:27px}.afaq-portal .lang{border-color:#d8cfb9;background:#fffdf8;color:#102b46}.afaq-portal .card,.afaq-portal .stat{background:#fffefa;border:1px solid #e4dfd2;border-radius:17px;box-shadow:0 11px 28px rgba(16,43,70,.075)}.afaq-portal .card{padding:24px}.afaq-portal .card h3{font-size:17px;color:#102b46;border-right:4px solid #caa04b;padding-right:10px}.afaq-portal .stat{padding:20px;position:relative;overflow:hidden}.afaq-portal .stat:before{content:'';position:absolute;top:0;right:0;left:0;height:4px;background:#caa04b}.afaq-portal .stat span{color:#687684;font-weight:700}.afaq-portal .stat b{color:#102b46;font-size:31px}.afaq-portal .stat em{color:#a47c2f}.afaq-portal .field label{color:#102b46;font-size:13px}.afaq-portal .field input,.afaq-portal .field select,.afaq-portal .field textarea{border-color:#dcd8cc;background:#fffefa;padding:11px;border-radius:10px}.afaq-portal .field input:focus,.afaq-portal .field select:focus,.afaq-portal .field textarea:focus{outline:2px solid rgba(202,160,75,.34);border-color:#caa04b}.afaq-portal .primary{background:#102b46;border-radius:10px;box-shadow:0 10px 20px rgba(16,43,70,.18)}.afaq-portal .primary:hover{background:#193a5a}.afaq-portal .outline{border-color:#caa04b;color:#102b46;background:#fffdf8}.afaq-portal .notice{background:#fbf6e8;border-right:4px solid #caa04b;color:#102b46}.afaq-portal .item{border-color:#e6e1d6}.afaq-portal .bubble{background:#f3ead3;color:#a47c2f}.afaq-portal .pill.good{background:#e5f0e8;color:#1e7459}
.role-deputy .top h2:after{content:' · لوحة الإدارة';font-size:14px;color:#a47c2f}.role-director .top h2:after{content:' · متابعة شاملة';font-size:14px;color:#a47c2f}.role-teacher .top h2:after{content:' · بوابة المعلم';font-size:14px;color:#a47c2f}.role-parent .top h2:after{content:' · شراكة الأسرة';font-size:14px;color:#a47c2f}
.auth{background:linear-gradient(135deg,#f7f6f1,#e7e9e7)}.auth-card{background:#fffefa;border:1px solid #e4dfd2;border-top:5px solid #caa04b;box-shadow:0 24px 60px rgba(16,43,70,.14)}.auth-card h2{color:#102b46}.auth-card .primary{background:#102b46}.auth-card .role-pick button{border-color:#d8cfb9;background:#fffdf8;color:#102b46}.auth-card .role-pick button.active{background:#102b46}.auth-card .back{color:#a47c2f}
.public{min-height:100vh;background:linear-gradient(135deg,#f7f6f1,#eef0ee)}.public header{background:#fffefa;border-bottom:1px solid #e2dccb}.public .brand{color:#102b46}.public .brand i{color:#caa04b}.public main{max-width:1000px;margin:auto;padding:45px 7%}.public .eyebrow{color:#a47c2f}.public h1{color:#102b46;font-size:40px}.public .card,.public .story{background:#fffefa;border:1px solid #e4dfd2;border-radius:16px;box-shadow:0 10px 24px rgba(16,43,70,.06)}.public .story{padding:20px;margin:12px 0}.public .notice{background:#fbf6e8;color:#102b46;border-right:4px solid #caa04b}.public .action{background:#fffefa;border-color:#e4dfd2;box-shadow:0 8px 18px rgba(16,43,70,.04)}.public .action .bubble{background:#f3ead3;color:#a47c2f}.public .outline{border-color:#caa04b;color:#102b46}
.public-nav{background:#102b46;border:0;padding:19px 8%}.public-nav button{color:#f9f4e9;font-weight:700}.public-nav button:hover{color:#e3c67e}
@media(max-width:760px){.afaq-portal .side{position:static;width:100%;min-height:auto}.afaq-portal .main{width:100%;margin:0;padding:24px 5%}.afaq-portal{display:block}.afaq-portal .stats{grid-template-columns:repeat(2,1fr)}.official-hero{margin:20px 14px;padding:35px 20px}.official-hero h1{font-size:36px}}
</style>`);
document.head.insertAdjacentHTML('beforeend',`<style>
:root{--brand:#102b46;--brand2:#193a5a}.auth-card .role-pick button.active{color:#fff!important}.role-deputy .top h2:after{content:none!important}.login-gold{background:#caa04b!important;color:#102b46!important;border-color:#caa04b!important}.landing.rebuilt{min-height:100vh;background:#f7f6f1}.landing.rebuilt .nav{background:#fffefa;border-bottom:1px solid #dfd8c8}.landing.rebuilt .nav .brand{color:#102b46}.landing.rebuilt .nav button{background:#caa04b;color:#102b46;border:0;font-weight:800}.home-stage{max-width:1200px;margin:auto;padding:62px 7% 38px;display:grid;grid-template-columns:1.1fr .9fr;gap:50px;align-items:center}.home-title{font-size:45px;line-height:1.38;color:#102b46;text-shadow:0 7px 16px #102b461c;margin:10px 0}.home-title span{color:#caa04b}.home-school{font-size:28px;font-weight:900;color:#102b46;border-right:6px solid #caa04b;padding-right:16px;box-shadow:12px 0 24px -18px #102b46}.home-copy{line-height:2;color:#536474}.home-logo-box{background:#fffefa;border:1px solid #e2dac8;border-radius:28px;padding:26px;box-shadow:0 20px 42px #102b4614;text-align:center}.home-logo-box img{width:250px;max-width:100%;object-fit:contain}.home-cta{display:block;margin:26px auto 0;background:#102b46!important}.home-links{max-width:1200px;margin:auto;padding:0 7% 45px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.home-links button{padding:18px;border:1px solid #e3dac6;border-right:5px solid #caa04b;border-radius:12px;background:#fffefa;color:#102b46;font-weight:800;text-align:right;box-shadow:0 7px 16px #102b460b}.home-links button:hover{background:#f4eddc}.certificate-sign{font-family:cursive;font-size:46px;color:#102b46;font-weight:bold}@media(max-width:760px){.home-stage{grid-template-columns:1fr;padding-top:34px}.home-links{grid-template-columns:1fr}.home-title{font-size:35px}}
</style>`);
landing=()=>{A().innerHTML=`<section class="landing rebuilt"><nav class="nav"><div class="brand"><i>✦</i> آفاق</div><button class="login-gold" onclick="auth('login')">تسجيل الدخول</button></nav><main class="home-stage"><div><div class="home-school">مدرسة بعيا للتعليم الأساسي والثانوي</div><h1 class="home-title">نصنع التميّز<br><span>ونفتح آفاق الإنجاز</span></h1><p class="home-copy">منصة مدرسية رسمية تجمع الميثاق والقيم الإيجابية والشراكة مع الأسرة والاحتفاء بالإنجاز.</p></div><div class="home-logo-box"><img src="/assets/ministry-logo-clean.png" alt="شعار وزارة التربية والتعليم"><button class="primary home-cta" onclick="auth('signup')">إنشاء حساب</button></div></main><div class="home-links">${['على خطى زايد','القيم الإيجابية','سفيرات الميثاق','الفصل الإيجابي','شراكة الأسرة','قصص النجاح'].map(x=>`<button onclick="publicPage('${x}')">${x}</button>`).join('')}</div></section>`};
function stats(){const can=['director','deputy'].includes(role);const card=(l,id,p)=>`<article class="stat" ${can?`onclick="dashboard('تفاصيل ${p}')" style="cursor:pointer"`:''}><span>${l}</span><b id="${id}">—</b>${can?'<em>اضغطي للتفاصيل</em>':''}</article>`;return `<div class="stats">${card('الطلاب المسجلون','stat-students','المشاركات')}${card('المشاركات','stat-participations','المشاركات')}${card('قصص النجاح','stat-stories','قصص النجاح')}${card('قيد المراجعة','stat-pending','قيد المراجعة')}${card('سفيرات الميثاق','stat-ambassadors','سفيرات الميثاق')}</div>`}
loadStats=async()=>{try{const [s,h]=await Promise.all([api('stats'),api('public/home')]);for(const [id,v] of Object.entries({'#stat-students':s.students,'#stat-participations':h.counts.participations,'#stat-stories':h.counts.stories,'#stat-pending':s.pending,'#stat-ambassadors':h.counts.ambassadors})){const x=document.querySelector(id);if(x)x.textContent=v}}catch{}};
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1600;cv.height=1000;const x=cv.getContext('2d');x.fillStyle='#fffefa';x.fillRect(0,0,1600,1000);x.fillStyle='#102b46';x.fillRect(0,0,1600,170);x.fillStyle='#caa04b';x.fillRect(0,170,1600,10);const logo=new Image();logo.src='/assets/ministry-logo-clean.png';await new Promise(r=>{logo.onload=r;logo.onerror=r});if(logo.naturalWidth)x.drawImage(logo,1090,38,330,105);x.textAlign='center';x.fillStyle='#102b46';x.font='bold 68px Arial';x.fillText('شهادة شكر وتقدير',760,320);x.fillStyle='#caa04b';x.fillRect(520,350,480,5);x.fillStyle='#132c45';x.font='33px Arial';x.fillText('تتقدم مدرسة بعيا للتعليم الأساسي والثانوي بالشكر والتقدير إلى',760,450);x.font='bold 62px Arial';x.fillText(c.owner_name,760,550);x.font='34px Arial';x.fillText(c.detail,760,650);x.textAlign='right';x.font='bold 28px Arial';x.fillText('مديرة المدرسة',1320,790);x.font='bold 48px cursive';x.fillText('يلوى المنصوري',1320,850);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
document.head.insertAdjacentHTML('beforeend',`<style>
.landing.rebuilt{background:#f7f6f1}.landing.rebuilt .home-stage{max-width:none;min-height:610px;background:linear-gradient(90deg,rgba(247,246,241,.96) 0%,rgba(247,246,241,.8) 32%,rgba(247,246,241,.08) 70%),url('/assets/uae-sky-hero.png') center/cover;grid-template-columns:360px 1fr;padding:44px 8%;gap:72px}.landing.rebuilt .home-school{grid-column:1/-1;background:#fffefa;border:1px solid #ddcfb2;border-right:6px solid #caa04b;border-radius:14px;padding:16px 24px;font-size:29px}.landing.rebuilt .home-logo-box{align-self:center}.landing.rebuilt .home-title{align-self:center;text-align:right;font-size:58px}.landing.rebuilt .home-cta{width:100%;margin:12px 0 0}.landing.rebuilt .home-login{width:100%;margin-top:10px;background:#fffefa;color:#102b46;border:1px solid #caa04b}.certificate-sign{font-family:cursive;font-size:46px;color:#102b46;font-weight:bold}@media(max-width:760px){.landing.rebuilt .home-stage{grid-template-columns:1fr;padding:25px 5%;gap:22px}.landing.rebuilt .home-school{font-size:22px}.landing.rebuilt .home-title{font-size:38px;text-align:center}}
</style>`);
landing=()=>{A().innerHTML=`<section class="landing rebuilt"><nav class="nav"><div class="brand"><i>✦</i> آفاق</div><img src="/assets/ministry-logo-clean.png" alt="شعار وزارة التربية والتعليم" style="height:54px;width:100px;object-fit:contain"></nav><main class="home-stage"><div class="home-school">مدرسة بعيا للتعليم الأساسي والثانوي</div><section class="home-logo-box"><img src="/assets/ministry-logo-clean.png" alt="شعار وزارة التربية والتعليم"><button class="primary home-cta" onclick="auth('signup')">إنشاء حساب</button><button class="home-login" onclick="auth('login')">تسجيل الدخول</button></section><h1 class="home-title">نصنع التميّز<br><span>ونفتح آفاق الإنجاز</span></h1></main><div class="home-links">${['على خطى زايد','القيم الإيجابية','سفيرات الميثاق','الفصل الإيجابي','شراكة الأسرة','قصص النجاح'].map(x=>`<button onclick="publicPage('${x}')">${x}</button>`).join('')}</div></section>`};
function stats(){const allowed=['director','deputy'].includes(role);const card=(l,id,p)=>`<article class="stat" ${allowed?`onclick="dashboard('تفاصيل ${p}')" style="cursor:pointer"`:''}><span>${l}</span><b id="${id}">—</b>${allowed?'<em>اضغطي للتفاصيل</em>':''}</article>`;return `<div class="stats">${allowed?card('الطلاب المسجلون','stat-students','المشاركات'):''}${card('المشاركات','stat-participations','المشاركات')}${card('قصص النجاح','stat-stories','قصص النجاح')}${card('قيد المراجعة','stat-pending','قيد المراجعة')}${card('سفيرات الميثاق','stat-ambassadors','سفيرات الميثاق')}</div>`}
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1080;cv.height=1500;const x=cv.getContext('2d');x.fillStyle='#fffefa';x.fillRect(0,0,1080,1500);x.fillStyle='#062d4b';x.beginPath();x.moveTo(0,0);x.lineTo(1080,0);x.lineTo(1080,170);x.lineTo(710,300);x.lineTo(370,300);x.lineTo(0,170);x.fill();x.fillStyle='#caa04b';x.fillRect(0,160,1080,10);x.beginPath();x.moveTo(0,1500);x.lineTo(1080,1500);x.lineTo(1080,1370);x.lineTo(710,1500);x.fill();x.fillStyle='#caa04b';x.fillRect(0,1360,1080,9);const l=new Image();l.src='/assets/ministry-logo-clean.png';await new Promise(r=>{l.onload=r;l.onerror=r});if(l.naturalWidth)x.drawImage(l,390,62,300,105);x.textAlign='center';x.fillStyle='#102b46';x.font='bold 39px Arial';x.fillText('مدرسة بعيا للتعليم الأساسي والثانوي',540,385);x.fillStyle='#caa04b';x.fillRect(270,420,540,4);x.fillStyle='#111';x.font='bold 75px Arial';x.fillText('شهادة شكر وتقدير',540,555);x.fillStyle='#102b46';x.font='32px Arial';x.fillText('تتقدم المدرسة بالشكر والتقدير إلى',540,680);x.fillStyle='#caa04b';x.font='bold 56px Arial';x.fillText('['+c.owner_name+']',540,795);x.fillStyle='#102b46';x.font='34px Arial';x.fillText(c.detail,540,900);x.font='bold 28px Arial';x.fillText('مديرة المدرسة',540,1110);x.font='bold 56px cursive';x.fillText('يلوى المنصوري',540,1195);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
landing();
valueForm=(type)=>{loadValueForm(type);return `<section class="card"><p class="empty">جارٍ تحميل القيمة الحالية…</p></section>`};
/* ضبط المقاسات الموحدة والنصوص الرسمية */
document.head.insertAdjacentHTML('beforeend',`<style>
html,body,#app{min-height:100%;background:#f7f5ef}
.landing.approved-home{width:100vw;min-height:100vh;padding:0;display:block;background:#f7f5ef}
.approved-home .approved-frame{width:100vw;max-width:none;height:100vh;min-height:590px;aspect-ratio:auto;margin:0;background-size:100% 100%;background-position:center;filter:none}
.auth,.dashboard{background:linear-gradient(90deg,rgba(247,245,239,.86),rgba(247,245,239,.65)),url('/assets/uae-sky-hero.png') center/cover fixed!important}
.auth{padding:34px 16px}.auth-card{background:rgba(255,254,250,.97)!important}
.dashboard .main{background:rgba(247,245,239,.80);min-height:100vh}.dashboard .side{background:rgba(255,254,250,.96)}
@media(max-width:760px){.approved-home .approved-frame{height:auto;min-height:0;aspect-ratio:1047/590;background-size:100% 100%}.auth{padding:20px 10px}.dashboard .main{background:rgba(247,245,239,.88)}}
</style>`);
loadValueForm=async(type)=>{try{const [settings,activity]=await Promise.all([api('settings'),api('student-activity?student='+encodeURIComponent(user.name))]);const value=type==='على خطى زايد'?settings.zayed_value:settings.positive_value;const kind=`${type}: ${value}`;const sent=activity.submissions.some(x=>x.kind===kind&&x.owner_email===user.email);const box=document.querySelector('#view');if(!box)return;if(sent){box.innerHTML=`<section class="card"><h3>${type}</h3><p class="notice">القيمة الحالية: <b>${value}</b></p><p class="empty">أرسلتِ دليلك لهذه القيمة بالفعل. عند تحديد نائب المدير قيمة جديدة ستتمكنين من المشاركة مرة أخرى.</p></section>`;return}box.innerHTML=`<div class="notice">القيمة الحالية: <b>${value}</b> — ارفعي دليلًا واحدًا فقط. تحصلين فورًا على شهادة شكر للمشاركة.</div><section class="card"><h3>${type}</h3><form onsubmit="submitValue(event,'${kind}')"><div class="field"><label>اكتبي وصف مشاركتك</label><textarea name="text" required placeholder="كيف طبقتِ القيمة؟"></textarea></div><div class="field"><label>الدليل: صورة أو فيديو حتى 100 MB</label><input name="proof" type="file" accept="image/*,video/*"></div><button class="primary">إرسال الدليل والحصول على الشهادة</button></form></section>`}catch(err){document.querySelector('#view').innerHTML=`<section class="card"><p class="empty">${err.message}</p></section>`}};
submitValue=async(e,kind)=>{e.preventDefault();const f=new FormData(e.target);try{await api('submissions',{student:user.name,grade:user.grade,section:user.section,owner_email:user.email,kind,text:f.get('text'),file:await asFile(e.target.proof)});const value=kind.split(': ').slice(1).join(': ');await api('certificates',{owner_email:user.email,owner_name:user.name,title:'شهادة شكر وتقدير',detail:`تعزيز قيمة "${value}"`});alert('تم حفظ الدليل وإصدار شهادة الشكر.');dashboard('شهاداتي')}catch(err){alert(err.message)}};
issueCharter=async()=>{if(!document.querySelector('#agree').checked)return alert('ضعي إشارة صح للموافقة على الميثاق.');try{await api('certificates',{owner_email:user.email,owner_name:user.name,title:'شهادة الالتزام بالميثاق',detail:'التعهد بالالتزام بميثاق المدرسة'});alert('تم إصدار شهادة الالتزام. ستجدينها في قسم شهاداتي.');dashboard('شهاداتي')}catch(err){alert(err.message)}};
loadPublicPage=async(name)=>{try{const h=await api('public/home');const box=document.querySelector('#publicContent');if(!box)return;if(name==='سفيرات الميثاق'){box.innerHTML=h.ambassadors.length?h.ambassadors.map(x=>`<article class="story"><b>✦ ${x.student}</b><small>سفيرة الميثاق · الصف ${x.grade}${x.section}</small></article>`).join(''):'<p class="empty">لا توجد سفيرات ميثاق معتمدات بعد.</p>'}else if(name==='قصص النجاح'){box.innerHTML=h.stories.length?h.stories.map(x=>`<article class="story"><b>${x.student}</b><small>سلوك إيجابي معتمد · ${x.grade}${x.section}</small><p>${x.text}</p>${x.file_url?`<a href="${x.file_url}" target="_blank">عرض الدليل المرفق</a>`:''}</article>`).join(''):'<p class="empty">سيتم نشر السلوكيات الإيجابية المعتمدة هنا.</p>'}else if(name==='شراكة الأسرة'){box.innerHTML=h.family_stories.length?h.family_stories.map(x=>`<article class="story"><b>${x.student}</b><small>قصة من وليّ الأمر · ${x.grade}${x.section}</small><p>${x.text}</p>${x.file_url?`<a href="${x.file_url}" target="_blank">عرض الدليل المرفق</a>`:''}</article>`).join(''):'<p class="empty">سيتم نشر قصص الأسرة المعتمدة هنا.</p>'}else if(name==='الفصل الإيجابي'){const winners=Object.fromEntries((h.class_winners||[]).map(x=>[x.grade,x.section]));box.innerHTML=`<section class="card"><h3>الفصل الإيجابي</h3>${['5','6','7'].map(g=>winners[g]?`<article class="story"><b>الصف ${g}</b><p>الشعبة الفائزة: <strong>${winners[g]}</strong></p></article>`:`<article class="story"><b>الصف ${g}</b><p class="empty">لم تُعتمد الشعبة الفائزة بعد.</p></article>`).join('')}</section>`}else if(name==='على خطى زايد'){box.innerHTML=`<section class="card"><h3>القيمة الحالية</h3><p class="notice">${h.values.zayed_value}</p><h3 style="margin-top:22px">قيم نعتز بها</h3><div class="action-grid">${['المسؤولية','الاحترام','التعاون','الانتماء','التسامح','المواطنة الصالحة'].map(x=>`<div class="action"><span class="bubble">✦</span><b>${x}</b></div>`).join('')}</div></section>`}else if(name==='القيم الإيجابية'){box.innerHTML=`<section class="card"><h3>القيمة الحالية</h3><p class="notice">${h.values.positive_value}</p><div class="action-grid">${['المساعدة','الصدق','الاحترام','التعاون','الإيثار','اللطف'].map(x=>`<div class="action"><span class="bubble">♡</span><b>${x}</b></div>`).join('')}</div></section>`}else{box.innerHTML=`<section class="card"><p class="empty">تظهر هنا المعلومات والنتائج المعتمدة الخاصة بقسم «${name}».</p></section>`}}catch(err){document.querySelector('#publicContent').innerHTML=`<p class="empty">${err.message}</p>`}};
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1080;cv.height=1600;const x=cv.getContext('2d');const t=new Image();t.src='/assets/certificate-approved-template.png';await new Promise(r=>{t.onload=r;t.onerror=r});if(t.naturalWidth)x.drawImage(t,0,0,1080,1600);else{x.fillStyle='#fff';x.fillRect(0,0,1080,1600)};const charter=/الميثاق|التعه/.test(`${c.title} ${c.detail}`);const match=String(c.detail||'').match(/[\[«"]([^\]»"]+)[\]»"]/);const value=match?match[1]:String(c.detail||'').replace(/^.*?(?:قيمة|تعزيز)\s*/,'').trim();x.fillStyle='#fff';x.fillRect(60,900,960,175);x.fillRect(70,1090,940,150);x.textAlign='center';x.fillStyle='#b37b12';x.font='bold 76px Arial';x.fillText(c.owner_name,540,1018);x.fillStyle='#102b46';x.font='bold 39px Arial';x.fillText('تقديرًا لـ',540,1140);x.font='36px Arial';x.fillText(charter?'"التعهد بالالتزام بميثاق المدرسة"':`"تعزيز قيمة ${value}"`,540,1210);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
landing();
/* النسخة المعتمدة من الواجهة الرئيسية والشهادة */
document.head.insertAdjacentHTML('beforeend',`<style>
.landing.approved-home{min-height:100vh;background:#f7f5ef;padding:22px;box-sizing:border-box}
.approved-home .approved-frame{position:relative;width:min(1047px,100%);aspect-ratio:1047/590;margin:0 auto;background:url('/assets/home-approved-reference.png') center/100% 100% no-repeat;filter:drop-shadow(0 15px 26px #102b4630)}
.approved-home .hotspot{position:absolute;z-index:2;display:block;border:0;background:transparent;cursor:pointer;border-radius:10px;color:transparent;font-size:0}
.approved-home .hotspot:focus-visible{outline:3px solid #c58b18;outline-offset:3px}
.approved-home .signup{left:8.7%;top:57.7%;width:25.3%;height:8.1%}
.approved-home .signin{left:8.7%;top:67.2%;width:25.3%;height:7.9%}
.approved-home .p0{left:3.6%;top:82.4%;width:15.3%;height:15.1%}.approved-home .p1{left:19.8%;top:82.4%;width:15.3%;height:15.1%}.approved-home .p2{left:36%;top:82.4%;width:15.3%;height:15.1%}.approved-home .p3{left:52.1%;top:82.4%;width:15.3%;height:15.1%}.approved-home .p4{left:68.3%;top:82.4%;width:15.3%;height:15.1%}.approved-home .p5{left:84.5%;top:82.4%;width:15.3%;height:15.1%}
@media(max-width:620px){.landing.approved-home{padding:8px;display:flex;align-items:flex-start}.approved-home .approved-frame{width:100%;min-width:0;margin-top:8px}.approved-home .hotspot{border-radius:5px}}
</style>`);
landing=()=>{const links=['قصص النجاح','شراكة الأسرة','الفصل الإيجابي','سفيرات الميثاق','القيم الإيجابية','على خطى زايد'];A().innerHTML=`<section class="landing approved-home"><main class="approved-frame" aria-label="بوابة آفاق الرسمية"><button class="hotspot signup" onclick="auth('signup')" aria-label="إنشاء حساب">إنشاء حساب</button><button class="hotspot signin" onclick="auth('login')" aria-label="تسجيل الدخول">تسجيل الدخول</button>${links.map((x,i)=>`<button class="hotspot p${i}" onclick="publicPage('${x}')" aria-label="${x}">${x}</button>`).join('')}</main></section>`};
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1080;cv.height=1600;const x=cv.getContext('2d');const t=new Image();t.src='/assets/certificate-approved-template.png';await new Promise(r=>{t.onload=r;t.onerror=r});if(t.naturalWidth)x.drawImage(t,0,0,1080,1600);else{x.fillStyle='#fff';x.fillRect(0,0,1080,1600)};const raw=String(c.detail||'');const found=raw.match(/\[([^\]]+)\]/);const value=found?found[1]:raw.replace(/^.*(?:قيمة|بمناسبة)\s*/,'').replace(/[.،]/g,'').trim();x.fillStyle='#fff';x.fillRect(125,800,830,150);x.fillRect(90,960,900,165);x.textAlign='center';x.fillStyle='#b37b12';x.font='bold 57px Arial';x.fillText('['+c.owner_name+']',540,892);x.fillStyle='#102b46';x.font='34px Arial';x.fillText(value?`تقديرًا لمشاركته في قيمة [${value}]`:'تقديرًا لمشاركته وتفاعله المتميّز',540,1058);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
landing();
/* final runtime overrides */
document.head.insertAdjacentHTML('beforeend',`<style>
.landing.approved-home{width:100vw!important;min-height:100vh!important;padding:0!important}.approved-home .approved-frame{width:100vw!important;max-width:none!important;height:100vh!important;min-height:590px!important;aspect-ratio:auto!important;margin:0!important;background-size:100% 100%!important;filter:none!important}@media(max-width:760px){.approved-home .approved-frame{height:auto!important;min-height:0!important;aspect-ratio:1047/590!important}}
</style>`);
landing=()=>{const links=['قصص النجاح','شراكة الأسرة','الفصل الإيجابي','سفيرات الميثاق','القيم الإيجابية','على خطى زايد'];A().innerHTML=`<section class="landing approved-home"><main class="approved-frame" aria-label="بوابة آفاق الرسمية"><button class="hotspot signup" onclick="auth('signup')" aria-label="إنشاء حساب">إنشاء حساب</button><button class="hotspot signin" onclick="auth('login')" aria-label="تسجيل الدخول">تسجيل الدخول</button>${links.map((x,i)=>`<button class="hotspot p${i}" onclick="publicPage('${x}')" aria-label="${x}">${x}</button>`).join('')}</main></section>`};
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1080;cv.height=1600;const x=cv.getContext('2d');const t=new Image();t.src='/assets/certificate-approved-template.png';await new Promise(r=>{t.onload=r;t.onerror=r});if(t.naturalWidth)x.drawImage(t,0,0,1080,1600);else{x.fillStyle='#fff';x.fillRect(0,0,1080,1600)};const charter=/الميثاق|التعه/.test(`${c.title} ${c.detail}`);const match=String(c.detail||'').match(/[\[«"]([^\]»"]+)[\]»"]/);const value=match?match[1]:String(c.detail||'').replace(/^.*?(?:قيمة|تعزيز)\s*/,'').trim();x.fillStyle='#fff';x.fillRect(60,900,960,175);x.fillRect(70,1090,940,150);x.textAlign='center';x.fillStyle='#b37b12';x.font='bold 76px Arial';x.fillText(c.owner_name,540,1018);x.fillStyle='#102b46';x.font='bold 39px Arial';x.fillText('تقديرًا لـ',540,1140);x.font='36px Arial';x.fillText(charter?'"التعهد بالالتزام بميثاق المدرسة"':`"تعزيز قيمة ${value}"`,540,1210);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
landing();
/* شهادة الشكر النهائية: القالب المعتمد دون أي تغيير في تصميمه */
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1080;cv.height=1623;const x=cv.getContext('2d');const t=new Image();t.src='/assets/certificate-final-template.png';await new Promise(r=>{t.onload=r;t.onerror=r});if(t.naturalWidth)x.drawImage(t,0,0,1080,1623);else{x.fillStyle='#fff';x.fillRect(0,0,1080,1623)};const charter=/الميثاق|التعه/.test(`${c.title} ${c.detail}`);x.fillStyle='#fff';x.fillRect(90,1070,900,205);x.textAlign='center';x.fillStyle='#b37b12';x.font='bold 76px Arial';x.fillText(c.owner_name,540,1165);x.fillStyle='#102b46';x.font='34px Arial';x.fillText(charter?'تقديراً لتعهدك بالالتزام بميثاق المدرسة':'تقديراً لمشاركتك في تعزيز القيم',540,1245);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
/* الهوية الموحدة لجميع البوابات */
document.head.insertAdjacentHTML('beforeend',`<style>
.dashboard,.afaq-portal,.public{min-height:100vh!important;background:linear-gradient(90deg,rgba(247,245,239,.90),rgba(247,245,239,.72)),url('/assets/uae-sky-hero.png') center/cover fixed!important}
.public{color:#102b46}.public header{background:rgba(255,254,250,.94)!important;border-bottom:3px solid #caa04b!important}.public main{background:rgba(255,254,250,.88);border-radius:20px;margin:28px auto;padding:30px;max-width:1100px;box-shadow:0 18px 42px rgba(16,43,70,.13)}
.dashboard .side,.afaq-portal .side{background:linear-gradient(180deg,#102b46,#071b2d)!important;border-left:3px solid #caa04b!important;box-shadow:0 0 30px rgba(16,43,70,.30)!important}
.dashboard .side .brand,.dashboard .side .user b,.afaq-portal .side .brand,.afaq-portal .side .user b{color:#fff!important}.dashboard .side .brand i,.afaq-portal .side .brand i{color:#d7aa45!important}.dashboard .side .user small,.afaq-portal .side .user small{color:#e6d39c!important}
.dashboard .side nav button,.afaq-portal .side nav button{color:#f7edd2!important;font-weight:800!important}.dashboard .side nav button.active,.dashboard .side nav button:hover,.afaq-portal .side nav button.active,.afaq-portal .side nav button:hover{background:#caa04b!important;color:#102b46!important;border-right:4px solid #fff4cf!important}.dashboard .side .logout,.afaq-portal .side .logout{color:#f6cf7a!important;font-weight:800!important}
.dashboard .main,.afaq-portal .main{background:rgba(247,245,239,.82)!important}
</style>`);
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1080;cv.height=1600;const x=cv.getContext('2d');const t=new Image();t.src='/assets/certificate-final-template.png';await new Promise(r=>{t.onload=r;t.onerror=r});if(t.naturalWidth)x.drawImage(t,0,0,1080,1600);else{x.fillStyle='#fff';x.fillRect(0,0,1080,1600)};const charter=/الميثاق|التعه/.test(`${c.title} ${c.detail}`);x.fillStyle='#fff';x.fillRect(60,980,960,305);x.textAlign='center';x.fillStyle='#b37b12';x.font='bold 104px Arial';x.fillText(c.owner_name,540,1125);x.fillStyle='#102b46';x.font='bold 46px Arial';x.fillText(charter?'تقديراً لتعهدك بالالتزام بميثاق المدرسة':'تقديراً لمشاركتك في تعزيز القيم',540,1240);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
/* شهادات الاعتماد للمعلمة وولي الأمر */
submitBehavior=async(e)=>{e.preventDefault();const f=new FormData(e.target);const cl=f.get('class').trim();try{await api('submissions',{student:f.get('student'),grade:cl[0]||'',section:cl.slice(-1)||'',kind:'سلوك إيجابي',text:f.get('text'),owner_email:user.email,owner_name:user.name});alert('تم إرسال الترشيح إلى نائب المديرة. عند اعتماده ستصل شهادة شكر إلى شهاداتك.');dashboard()}catch(err){alert(err.message)}};
submitStory=async(e,kind)=>{e.preventDefault();const f=new FormData(e.target);const cl=f.get('class').trim();try{await api('stories',{student:f.get('student'),grade:cl[0]||'',section:cl.slice(-1)||'',author:user.name,author_email:user.email,source_role:kind,text:f.get('text'),file:await asFile(e.target.proof)});alert('تم حفظ القصة وإرسالها إلى نائب المديرة. عند اعتمادها ستصل شهادة شكر إلى شهاداتك.');dashboard(kind==='parent'?'طلباتي السابقة':'الرئيسية')}catch(err){alert(err.message)}};
downloadCertificate=async(i)=>{const c=window.afaqCertificates?.[i];if(!c)return;const cv=document.createElement('canvas');cv.width=1080;cv.height=1600;const x=cv.getContext('2d');const t=new Image();t.src='/assets/certificate-final-template.png';await new Promise(r=>{t.onload=r;t.onerror=r});if(t.naturalWidth)x.drawImage(t,0,0,1080,1600);else{x.fillStyle='#fff';x.fillRect(0,0,1080,1600)};const detail=String(c.detail||'');const charter=/الميثاق|التعه/.test(`${c.title} ${detail}`);const phrase=detail==='خالص الامتنان لجهودك المباركة'||detail.startsWith('تقديراً لمشاركتكم')?detail:(charter?'تقديراً لتعهدك بالالتزام بميثاق المدرسة':'تقديراً لمشاركتك في تعزيز القيم');x.fillStyle='#fff';x.fillRect(60,980,960,305);x.textAlign='center';x.fillStyle='#b37b12';x.font='bold 104px Arial';x.fillText(c.owner_name,540,1125);x.fillStyle='#102b46';x.font='bold 46px Arial';x.fillText(phrase,540,1240);const a=document.createElement('a');a.download=`شهادة-${c.owner_name}-${c.id}.png`;a.href=cv.toDataURL('image/png');a.click()};
